routes/web.php
<?php

//use App\Http\Controllers\frontend\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

// todo                                      MESSAGE
//  Everything is being done through Cache, to know on which URL are users and what language should be.


//Route::middleware('domain')->get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// ========================================= Back End ========================================= //
Route::group(['prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend', 'middleware'=> 'auth'], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('/domain', DomainController::class);
    Route::resource('/header', HeaderController::class);
    Route::resource('/info', InfoController::class);
    Route::resource('/news', NewsController::class);
    Route::resource('/destination', DestinationController::class);
        Route::post('/destination/delete/image/{id}', 'DestinationController@deleteOne')->name('delete-one-picture-gallery');
    Route::resource('/footer', FooterController::class);
    Route::resource('/content', ContentController::class);
    Route::resource('/pages', PagesController::class);
        Route::post('/pages/delete/image/{id}', 'PagesController@deleteOne')->name('delete-one-picture-gallery-pages');
    Route::resource('/brochure', BrochuresController::class);

});
// --------------------------------------------------------------------------------------------- //





// ========================================= Front End ========================================= //
Route::group([], function() { //'prefix' => '/admin', 'middleware'=> ['domain']
    Route::get('/', function (){ return redirect()->route('home');} );
    Route::get('/home', [App\Http\Controllers\Frontend\HomeController::class, 'home'])->name('home');
    Route::get('/brochure', [App\Http\Controllers\Frontend\HomeController::class, 'brochure'])->name('brochure');
    Route::get('/page/{id}', [App\Http\Controllers\Frontend\HomeController::class, 'page'])->name('page');
    Route::get('/destination', [App\Http\Controllers\Frontend\HomeController::class, 'destination'])->name('destination');
    Route::get('/destination/{id}', [App\Http\Controllers\Frontend\HomeController::class, 'destinationSingle'])->name('destination.single');
    Route::get('/hotel', [App\Http\Controllers\Frontend\HomeController::class, 'hotelSingle'])->name('hotel.single');

});
// --------------------------------------------------------------------------------------------- //




Route::get('/code/run/{type}', function ($type){
//    dd($type);
    $command = '';
    if ($type == 'fresh--seed' || $type == '1'){
        $command = 'migrate:fresh --seed';
        $message = 'fresh --seed [success]';
    }
    elseif ($type == 'migrate' || $type == '2'){
        $command = 'migrate';
        $message = 'migrate [success]';
    }
    elseif ($type == 'storagelink' || $type == '3'){
        $command = 'storage:link';
        $message = 'storage:link [success]';
    }
    elseif ($type == 'job' || $type == '4'){
        $command = 'queue:work';
        $message = 'job run  [success]';
    }
    elseif ($type == 'clear' || $type == '5'){
        $message = 'clear  [success]';
        Artisan::call('config:clear');
        Artisan::call('route:clear');
        Artisan::call('view:clear');
        Artisan::call('event:clear');
        Artisan::call('cache:clear');
        return dd('dun '.$message);
    }
    else{
        echo 'commands: fresh--seed, migrate, storagelink';
        dd('error: no this command please add');
    }

    $artisan = Artisan::call($command);
    return dd('dun '.$message.' |  artisan command: '.$artisan);
});

app/Models/Brochure.php
<?php

namespace App\Models;

use App\MyHellper\DomainHellper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brochure extends LocalizedModel
{
    use HasFactory;

    protected $table ='brochures';
    protected $fillable = [
        'path',
    ];


}

app/Models/LocalizedModel.php
<?php

namespace App\Models;

use App\MyHellper\DomainHellper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LocalizedModel extends Model
{
    use HasFactory;

    public function localizations()
    {
        return $this->hasMany($this->getClassName());
    }

    public function getClassName()
    {
        return get_class($this) . 'Translate';
    }

    public function getAccesserAttribute()
    {
        return DomainHellper::attribute($this);
    }

    public function translateLang()
    {
        // для того чтобы елси был PageItem стал page_item
        $str = lcfirst(class_basename($this));
        $str = preg_replace("/[A-Z]/", '_'.'$0', $str);
        $translateModel = get_class($this).'Translate';
        $lowercase = strtolower($str);
        return $this->hasMany($translateModel,$lowercase.'_id','id');
    }

}

app/Http/Controllers/Backend/BrochuresController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Brochure;
use App\Models\BrochureTranslate;
use App\MyHellper\HellperFiles;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BrochuresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $brochures = Brochure::all();
        return view('backend.dashboard.brochure.index', compact('brochures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.brochure.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
//        dd($request->all());
        DB::beginTransaction();
        $filepicture = $request['image_one'];
        $firstfile = HellperFiles::FileOne($filepicture, null, 'Brochure');
        $pathOne = HellperFiles::PathFile($firstfile);
        $brochure = new Brochure();
        $brochure->path = $pathOne ;
        $brochure->save();

        foreach ($request->langs as $key => $lang){
            $brochure->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'sub_title' => $lang['sub_title'] ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('brochure.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $brochure = Brochure::findorFail($id)->load('translateLang');
        return view('backend.dashboard.brochure.edit', compact('brochure'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $brochure = Brochure::findorFail($id);
        DB::beginTransaction();
        if ($request['image_one']){
            $filepicture = $request['image_one'];
            HellperFiles::FilesOneDelete($brochure->path);
            $firstfile = HellperFiles::FileOne($filepicture, null, 'Brochure');
            $pathOne = HellperFiles::PathFile($firstfile);
            $brochure->path = $pathOne ;
        }
        $deleteResult = $brochure->localizations()->delete();
        if (!$deleteResult) {
            DB::rollBack();
            return redirect()->back()->with(['error' => 'Something went wrong.'])->withInput();
        }
        $brochure->save();

        //ADDING elements in ProductTr
        foreach ($request->langs as $key => $lang){
            $brochure->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'sub_title' => $lang['sub_title'] ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('brochure.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $brochure = Brochure::findorFail($id);
        HellperFiles::FilesOneDelete($brochure->path);
        $brochure->delete();
        $brochure->localizations()->delete();
        return redirect()->route('brochure.index')->with(['message' => 'Deleted.']);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.dashboard');
    }
}

resources/views/backend/dashboard/brochure/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('brochure.index')}}">Brochures</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Create</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('brochure.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf

                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($domainsGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-6">
                                                            <label for="exampleInputPassword1">Sub Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][sub_title]" id="exampleInputPassword1" placeholder="Sub Title" value="{{ old('langs['.$item->lang.'][sub_title]') }}"  >
                                                        </div>
                                                        <div class="form-group col-6">
                                                            <label for="exampleInputPassword1">Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][title]" id="exampleInputPassword1" placeholder="Title" value="{{ old('langs['.$item->lang.'][title]') }}"  >
                                                        </div>
                                                        <div class="form-group col-12">
                                                            <label for="exampleInputPassword2">Description</label>
                                                            <textarea class="summernote" name="langs[{{ $item->lang }}][description]">{{ old('langs['.$item->lang.'][description]') }}</textarea>
                                                        </div>
                                                        <input type="hidden" style="display: none" name="langs[{{ $item->lang }}][domain_id]" value="{{$item->id}}">
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <div class="card-body row">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">Image</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image_one" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/brochure/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
@endsection

@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('brochure.index')}}">Brochures</a></li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Edit</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('brochure.update', $brochure->id)}}" method="POST" enctype="multipart/form-data">
                                    @method('PUT')
                                    @csrf
                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($domainsGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-6">
                                                            <label for="exampleInputPassword1">Sub Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][sub_title]" id="exampleInputPassword1" placeholder="Sub Title" value="{{isset($brochure->translateLang[$key]->sub_title) ? $brochure->translateLang[$key]->sub_title : ''}}">
                                                        </div>
                                                        <div class="form-group col-6">
                                                            <label for="exampleInputPassword1">Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][title]" id="exampleInputPassword1" placeholder="Title" value="{{isset($brochure->translateLang[$key]->title) ? $brochure->translateLang[$key]->title : ''}}">
                                                        </div>
                                                        <div class="form-group col-12">
                                                            <label for="exampleInputPassword2">Description</label>
                                                            <textarea class="summernote" name="langs[{{ $item->lang }}][description]">{{ isset($brochure->translateLang[$key]->description) ? $brochure->translateLang[$key]->description : '' }}</textarea>
                                                        </div>
                                                        <input type="hidden" style="display: none" name="langs[{{ $item->lang }}][domain_id]" value="{{$item->id}}">
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <div class="card-body row">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image_one" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                        <img style="width: 40%" src="{{asset($brochure->path)}}" alt="">
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/brochure/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Company</title>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Brochures</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Brochures</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @if(count($brochures) == 0)
                            <div>
                                <a href="{{route('brochure.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                            @endif
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Sub Title</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($brochures as $item)
                                        <tr>
                                            <td style="width: 15%"><img src="{{asset($item->path)}}" alt="" style="width: 100%"></td>
                                            <td>{{ $item->accesser->sub_title }}</td>
                                            <td>{{ $item->accesser->title }}</td>
                                            <td>{!! $item->accesser->description !!}</td>
                                            <td>
                                                <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("brochure.edit", $item->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                        <form method="POST" action="{{ route("brochure.destroy" , $item->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                                <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                    <i class="fa fa-trash"></i>
                                                                </button>
                                                            </a>
                                                        </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection