routes/web.php
<?php

//use App\Http\Controllers\frontend\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

// todo                                      MESSAGE
//  Everything is being done through Cache, to know on which URL are users and what language should be.


//Route::middleware('domain')->get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// ========================================= Back End ========================================= //
Route::group(['prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend', 'middleware'=> 'auth'], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('/domain', DomainController::class);
    Route::resource('/header', HeaderController::class);
    Route::resource('/info', InfoController::class);
    Route::resource('/news', NewsController::class);
    Route::resource('/destination', DestinationController::class);
        Route::post('/destination/delete/image/{id}', 'DestinationController@deleteOne')->name('delete-one-picture-gallery');
    Route::resource('/footer', FooterController::class);
    Route::resource('/content', ContentController::class);
    Route::resource('/pages', PagesController::class);
        Route::post('/pages/delete/image/{id}', 'PagesController@deleteOne')->name('delete-one-picture-gallery-pages');
    Route::resource('/brochure', BrochuresController::class);

});
// --------------------------------------------------------------------------------------------- //





// ========================================= Front End ========================================= //
Route::group([], function() { //'prefix' => '/admin', 'middleware'=> ['domain']
    Route::get('/', function (){ return redirect()->route('home');} );
    Route::get('/home', [App\Http\Controllers\Frontend\HomeController::class, 'home'])->name('home');
    Route::get('/brochure', [App\Http\Controllers\Frontend\HomeController::class, 'brochure'])->name('brochure');
    Route::get('/page/{id}', [App\Http\Controllers\Frontend\HomeController::class, 'page'])->name('page');
    Route::get('/destination', [App\Http\Controllers\Frontend\HomeController::class, 'destination'])->name('destination');
    Route::get('/destination/{id}', [App\Http\Controllers\Frontend\HomeController::class, 'destinationSingle'])->name('destination.single');
    Route::get('/hotel', [App\Http\Controllers\Frontend\HomeController::class, 'hotelSingle'])->name('hotel.single');

});
// --------------------------------------------------------------------------------------------- //




Route::get('/code/run/{type}', function ($type){
//    dd($type);
    $command = '';
    if ($type == 'fresh--seed' || $type == '1'){
        $command = 'migrate:fresh --seed';
        $message = 'fresh --seed [success]';
    }
    elseif ($type == 'migrate' || $type == '2'){
        $command = 'migrate';
        $message = 'migrate [success]';
    }
    elseif ($type == 'storagelink' || $type == '3'){
        $command = 'storage:link';
        $message = 'storage:link [success]';
    }
    elseif ($type == 'job' || $type == '4'){
        $command = 'queue:work';
        $message = 'job run  [success]';
    }
    elseif ($type == 'clear' || $type == '5'){
        $message = 'clear  [success]';
        Artisan::call('config:clear');
        Artisan::call('route:clear');
        Artisan::call('view:clear');
        Artisan::call('event:clear');
        Artisan::call('cache:clear');
        return dd('dun '.$message);
    }
    else{
        echo 'commands: fresh--seed, migrate, storagelink';
        dd('error: no this command please add');
    }

    $artisan = Artisan::call($command);
    return dd('dun '.$message.' |  artisan command: '.$artisan);
});

app/Http/Controllers/Backend/BrochuresController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Brochure;
use App\Models\BrochureTranslate;
use App\MyHellper\HellperFiles;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BrochuresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $brochures = Brochure::all();
        return view('backend.dashboard.brochure.index', compact('brochures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.brochure.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
//        dd($request->all());
        DB::beginTransaction();
        $filepicture = $request['image_one'];
        $firstfile = HellperFiles::FileOne($filepicture, null, 'Brochure');
        $pathOne = HellperFiles::PathFile($firstfile);
        $brochure = new Brochure();
        $brochure->path = $pathOne ;
        $brochure->save();

        foreach ($request->langs as $key => $lang){
            $brochure->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'sub_title' => $lang['sub_title'] ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('brochure.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $brochure = Brochure::findorFail($id)->load('translateLang');
        return view('backend.dashboard.brochure.edit', compact('brochure'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $brochure = Brochure::findorFail($id);
        DB::beginTransaction();
        if ($request['image_one']){
            $filepicture = $request['image_one'];
            HellperFiles::FilesOneDelete($brochure->path);
            $firstfile = HellperFiles::FileOne($filepicture, null, 'Brochure');
            $pathOne = HellperFiles::PathFile($firstfile);
            $brochure->path = $pathOne ;
        }
        $deleteResult = $brochure->localizations()->delete();
        if (!$deleteResult) {
            DB::rollBack();
            return redirect()->back()->with(['error' => 'Something went wrong.'])->withInput();
        }
        $brochure->save();

        //ADDING elements in ProductTr
        foreach ($request->langs as $key => $lang){
            $brochure->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'sub_title' => $lang['sub_title'] ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('brochure.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $brochure = Brochure::findorFail($id);
        HellperFiles::FilesOneDelete($brochure->path);
        $brochure->delete();
        $brochure->localizations()->delete();
        return redirect()->route('brochure.index')->with(['message' => 'Deleted.']);
    }
}

app/Http/Controllers/Backend/ContentController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Content\CreateRequest;
use App\Http\Requests\Content\EditRequest;
use App\Models\Content;
use App\MyHellper\HellperFiles;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $contents = Content::all();
        return view('backend.dashboard.content.index', compact('contents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.content.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
//        dd($request->all());

        DB::beginTransaction();
        $filepicture = $request['image_one'];
        $firstfile = HellperFiles::FileOne($filepicture, null, 'Content');
        $pathOne = HellperFiles::PathFile($firstfile);
        $content = new Content();
        $content->path = $pathOne ;
        $content->save();
        foreach ($request->langs as $key => $lang){
            $content->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('content.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $content = Content::findorFail($id)->load('translateLang');
        return view('backend.dashboard.content.edit', compact('content'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EditRequest $request, $id)
    {

        $content = Content::findorFail($id);
        DB::beginTransaction();
        if ($request['image_one']){
            $filepicture = $request['image_one'];
            HellperFiles::FilesOneDelete($content->path);
            $firstfile = HellperFiles::FileOne($filepicture, null, 'Content');
            $pathOne = HellperFiles::PathFile($firstfile);
            $content->path = $pathOne ;
        }
        $deleteResult = $content->localizations()->delete();
        if (!$deleteResult) {
            DB::rollBack();
            return redirect()->back()->with(['error' => 'Something went wrong.'])->withInput();
        }
        $content->save();
        //ADDING elements in ProductTr
        foreach ($request->langs as $key => $lang){
            $content->localizations()->create([
                'domain_id' => $lang['domain_id'] ,
                'lang' => $key ,
                'title' => $lang['title'] ,
                'description' => $lang['description'] ,
            ]);
        }

        DB::commit();

        return redirect()->route('content.index')->with(['message' => 'Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $content = Content::findorFail($id);
        HellperFiles::FilesOneDelete($content->path);
        $content->delete();
        $content->localizations()->delete();
        return redirect()->route('content.index')->with(['message' => 'Deleted.']);
    }

}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.dashboard');
    }
}

app/Http/Controllers/Backend/DomainController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Domain\CreateRequest;
use App\Http\Requests\Domain\EditRequest;
use App\Models\Domain;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class DomainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $domains = Domain::all();
        return view('backend.dashboard.domain.index', compact('domains'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.domain.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $domain = new Domain();
        $domain->domain = $request->domain;
        $domain->name = $request->name;
        $domain->lang = $request->lang;
        $domain->save();
        return redirect()->route('domain.index')->with('message', 'Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $domain = Domain::findOrFail($id);
        return view('backend.dashboard.domain.edit', compact('domain'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EditRequest $request, $id)
    {
        $domain = Domain::findOrFail($id);
        $domain->domain = $request->domain;
        $domain->name = $request->name;
        $domain->save();
        return redirect()->route('domain.index')->with('message', 'Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $domain = Domain::findOrFail($id);
        $domain->delete();
        Cache::forget('domain_id');
        Cache::forget('domain');
        return redirect()->route('domain.index')->with('message', 'Successfully');
    }
}

resources/views/backend/components/css.blade.php
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/fontawesome-free/css/all.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">

<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/jqvmap/jqvmap.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('assets/backend/dist/css/adminlte.min.css')}}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('assets/backend/plugins/daterangepicker/daterangepicker.css')}}">
<!-- summernote -->
<link rel="stylesheet" href="{{asset('/assets/backend/plugins/summernote/summernote-bs4.css')}}">

<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

<link rel="stylesheet" href="{{asset('/assets/backend/custom/css/custom.css')}}">

resources/views/backend/components/flashMessage.blade.php
@if(Session::has('message'))
    <div class="container" style="margin-top: 15px;">
        <div class="alert alert-success">
            <em>{!! session('message') !!}</em>
        </div>
    </div>
@endif
@if(Session::has('error'))
    <div class="container" style="margin-top: 15px;">
        <div class="alert alert-danger">
            <em>{!! session('error') !!}</em>
        </div>
    </div>
@endif

@if (count($errors) > 0)
    <div class="container" style="margin-top: 15px;">
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <em>{{ $error }}</em> <br>
            @endforeach
        </div>
    </div>
@endif

resources/views/backend/components/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; 2022-2022 <a href="javascript:;">Travel</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 0.0.1
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/backend/components/js.blade.php
<!-- jQuery -->
<script src="{{asset('assets/backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('assets/backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('assets/backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{asset('assets/backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('assets/backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('assets/backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('assets/backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('assets/backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('assets/backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('assets/backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('assets/backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('assets/backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets/backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('assets/backend/dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('assets/backend/dist/js/demo.js')}}"></script>


<script src="{{asset('/assets/backend/custom/js/ImgDeleteCU.js')}}"></script>


<!-- Summernote -->
<script src="{{asset('/assets/backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- Page specific script -->
<script>
    $(function summer () {
        // Summernote
        $('.summernote').summernote({
            height: 200
        });
        // CodeMirror
        CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
            mode: "htmlmixed",
            theme: "monokai"
        });
    })

</script>

resources/views/backend/components/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                Go to Web
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right custom-style-left">
                <span class="dropdown-header">Websites</span>
                @foreach($domainsGLOBAL as $dom)
                    <a class="dropdown-item" href="https://{{ $dom->domain }}/home" target="_blank">
                        {{$dom->domain}}
                    </a>
                @endforeach
            </div>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-th-large"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">{{ Auth::user()->name }}</span>
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>

    </ul>
</nav>

resources/views/backend/components/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/admin" class="brand-link">
        <img src="{{asset('assets/backend/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Admin panel</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('assets/backend/custom/image/Businessman-160x160.png')}}" class="img-circle elevation-2" alt="User Image" style="background-color: white;">
            </div>
            <div class="info">
                <a href="#" class="d-block">Administrator</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{route('domain.index')}}" class="nav-link {{ Route::currentRouteNamed(['domain.index', 'domain.edit', 'domain.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-bezier-curve"></i>
                        <p>
                            Domain
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('header.index')}}" class="nav-link {{ Route::currentRouteNamed(['header.index', 'header.edit', 'header.create']) ? 'active' : '' }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>
                            Header
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('destination.index')}}" class="nav-link {{ Route::currentRouteNamed(['destination.index', 'destination.edit', 'destination.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-arrows-turn-to-dots"></i>
                        <p>
                            Destinations
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('news.index')}}" class="nav-link {{ Route::currentRouteNamed(['news.index', 'news.edit', 'news.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-diagram-next"></i>
                        <p>
                            News
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('info.index')}}" class="nav-link {{ Route::currentRouteNamed(['info.index', 'info.edit', 'info.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-hashtag"></i>
                        <p>
                            Info
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('content.index')}}" class="nav-link {{ Route::currentRouteNamed(['content.index', 'content.edit', 'content.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-align-left"></i>
                        <p>
                            Content
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('pages.index')}}" class="nav-link {{ Route::currentRouteNamed(['pages.index', 'pages.edit', 'pages.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-file"></i>
                        <p>
                            Pages
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('brochure.index')}}" class="nav-link {{ Route::currentRouteNamed(['brochure.index', 'brochure.edit', 'brochure.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-pager"></i>
                        <p>
                            Brochure
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('footer.index')}}" class="nav-link {{ Route::currentRouteNamed(['footer.index', 'footer.edit', 'footer.create']) ? 'active' : '' }}">
                        <i class="nav-icon fa-solid fa-arrows-down-to-line"></i>
                        <p>
                            Footer
                        </p>
                    </a>
                </li>






                {{--<li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far fa-envelope"></i>
                        <p>
                            Droup Down
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Inbox</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Compose</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Read</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far fa-image"></i>
                        <p>
                            Single
                        </p>
                    </a>
                </li>--}}
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/backend/components/translate.blade.php
<ul class="nav nav-tabs" id="custom-tabs-two-tab" role="tablist">
    @foreach($domainsGLOBAL as $key => $item)
            {{--activ class in a teg--}}
            <li class="nav-item">
                <a class="nav-link  @if($key == 0) active @endif" id="custom-tabs-two-{{ $item->lang }}-tab" data-toggle="pill" href="#{{ $item->lang}}" role="tab" aria-controls="custom-tabs-two-{{ $item->lang }}" aria-selected="true">
                    {{ $item->name }}
                </a>
            </li>
    @endforeach
</ul>